# Generated by Django 4.1.4 on 2022-12-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankdetails_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('sender_account_number', models.UUIDField()),
                ('reciever_account_number', models.UUIDField()),
                ('amount', models.IntegerField()),
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
