# Generated by Django 4.1.4 on 2022-12-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction_remove_bankdetails_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reciever_account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_account_number',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
