# Generated by Django 4.1.4 on 2022-12-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_transaction_reciever_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever_account_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account_number',
            field=models.IntegerField(default=None),
        ),
    ]
