# Generated by Django 4.1.4 on 2022-12-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transaction_reciever_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever_account_number',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_number',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
