# Generated by Django 4.1.4 on 2022-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_bankdetails_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_type',
            field=models.CharField(default='DEBIT', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever_account_number',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_number',
            field=models.CharField(max_length=1000000),
        ),
    ]
