# Generated by Django 4.1.4 on 2022-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_bankdetails_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditcarddetails',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('creditcardnumber', models.AutoField(primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(max_length=1000000)),
                ('creditLimit', models.IntegerField(default=50000)),
            ],
        ),
    ]
